### ISSUE TITLE
Unexpected behavior with `rtqc_spike` function

### ISSUE THREAD

**Issue by mountaindboz** [ODWG/ODWGtools#1]
I'm getting some unexpected behavior when using the `rtqc_spike` function with dynamic spike thresholds. When using 20 and 30% of the spike reference values for the thresholds, some of the values are being flagged as "fail" when they shouldn't be. In the example below, row 15 is being marked as "fail" when it should be "suspect", and row 16 is being marked as "fail" when it should be "pass".

```
df <- structure(list(DateTime = structure(c(1436169600, 1436170500, 
                                            1436171400, 1436172300, 1436173200, 1436174100, 1436175000, 1436175900, 
                                            1436176800, 1436177700, 1436178600, 1436179500, 1436180400, 1436181300, 
                                            1436182200, 1436183100, 1436184000, 1436184900, 1436185800, 1436186700
), tzone = "Etc/GMT+8", class = c("POSIXct", "POSIXt")), Turbidity = c(8.6, 
                                                                       8.7, 9, 9.3, 9.8, 9.5, 10, 9.9, 10, 8.7, 9.1, 9, 21, 19, 15, 
                                                                       18, 16, 14, 13, 12)), row.names = c(NA, -20L), class = c("tbl_df", 
                                                                                                                                "tbl", "data.frame"))

df %>% 
  mutate(
    # spike test with dynamic thresholds (20 and 30% of the spike reference)
    qual_spike = rtqc_spike(
      Turbidity, 
      c((lag(Turbidity) + lead(Turbidity))/2 * 0.2, (lag(Turbidity) + lead(Turbidity))/2 * 0.3)
    ),
    spike_ref = (lag(Turbidity) + lead(Turbidity))/2,
    val_minus_spref = abs(Turbidity - spike_ref),
    spike_ref_20 = spike_ref * 0.2,
    spike_ref_30 = spike_ref * 0.3
  )

```

**Comment by mkoohafkan** [comment]
`rtqc_spike` expects a length 2 vector for the argument `spike.threshold`. The test is based on the QARTOD manual specification which tests for spikes of an **absolute** magnitude, with different thresholds for assigning "suspect" and "fail" flags. In your example, you are passing a length 40 vector to `spike.threshold`, presumably because you want to test for spikes of a **relative** magnitude (20% change and 30% change from previous value, respectively). The function only uses the first two values of your length 40 vector for the "suspect" and "fail" thresholds, respectively.

I see two options for moving forward:

1. Continue to follow the QARTOD manual specification, and add a catch in the function to throw an error if anything other than a length 2 vector is supplied.
2. Break from the QARTOD manual specification and allow users to provide a length 2 *list* of either vectors (each of same length as data) or single values.

**Comment by mountaindboz** [comment]
Hmm, I was trying to pass a length 2 vector to the `spike.threshold` argument. I guess not though, which explains the strange results.

The QARTOD manual does mention that the thresholds for the spike test may be fixed or dynamically established. I was trying to use the latter approach using relative magnitudes of the neighboring values (1 before and 1 after). It would be nice to allow for this use case in addition to using absolute or fixed thresholds. I would choose whichever method is most simple or straightforward... either by modifying the existing function or to create a new one.

**Comment by mkoohafkan** [comment]
see c3ed40a1ded3f335d26447e169ca553b67f80473
